#server:
#  port: 80
custom.domain: www.ancestry.com

spring:
    url: jdbc:h2:mem:vk_service;DB_CLOSE_ON_EXIT=FALSE
#    datasource.url: jdbc:h2:file:/home/alex/db/vk;DB_CLOSE_ON_EXIT=FALSE
    datasource.username: sa
    datasource.password: sa
    datasource.driverClassName: org.h2.Driver

    jpa.database-platform: org.hibernate.dialect.H2Dialect
    jpa.show-sql: true
    h2.console.enabled: true
    h2.console.path: /h2-console