custom.domain: www.ancestry.com
custom.clientID: 5538646
custom.clientSecret: 6I04Vp18QEGvjUaLfOPE
custom.redirectUrl: http://www.ancestry.com:8080/authorization

spring:
    url: jdbc:h2:mem:vk_service;DB_CLOSE_ON_EXIT=FALSE
    datasource.username: sa
    datasource.password: sa
    datasource.driverClassName: org.h2.Driver

    jpa.database-platform: org.hibernate.dialect.H2Dialect
    jpa.show-sql: true
    h2.console.enabled: true
    h2.console.path: /h2-console